name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: npm install && npm run build
