name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: npm install && npm run test
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.github_token }}
